# -*- coding: utf-8 -*-
"""Machine1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BsPD1OgjZwhAQa5qRqcgdDuIMnXjUqvw
"""

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# 1. Carregar os dados (Já vem pronto no sklearn)
iris = load_iris()
X = iris.data  # Características: comprimento e largura de pétalas/sépalas
y = iris.target # O que queremos prever: o tipo da flor (0, 1 ou 2)

# 2. Dividir os dados: 80% para treinar o robô e 20% para testar se ele aprendeu
X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.2, random_state=42)

# 3. Escolher o modelo (Árvore de Decisão)
modelo = DecisionTreeClassifier()

# 4. TREINAMENTO: Onde a "mágica" acontece
modelo.fit(X_treino, y_treino)

# 5. PREVISÃO: Testando o modelo com dados que ele nunca viu
previsoes = modelo.predict(X_teste)

# 6. RESULTADO: Qual foi a precisão?
precisao = accuracy_score(y_teste, previsoes)

print(f"Resultado do Treinamento:")
print(f"A precisão do modelo foi de: {precisao * 100:.2f}%")

# Exemplo de previsão manual com novas medidas:
nova_flor = [[5.1, 3.5, 1.4, 0.2]]
especie = iris.target_names[modelo.predict(nova_flor)[0]]
print(f"Para as medidas {nova_flor}, a espécie prevista é: {especie}")